### PR TITLE
Add blastdb example data

### PR DESCRIPTION
**Pull request by jvfe**
Changes made:
 * Add module to bioprov.data corresponding to a BLASTdb

Database was made using `makeblastdb`, by using the hits from both genomes in bioprov.data.genomes + the 200 first sequences from [MEGARes v2.0](https://megares.meglab.org/download/index.php)

### CODE REVIEW

**Review by vinisalazar — APPROVED** [review]
Great work, LGTM!

**Comment by vinisalazar** [comment]
BTW, I liked the "/" operator in Path objects which you submitted in #24 . Did not know about that one.

**Comment by jvfe** [comment]
> BTW, I liked the "/" operator in Path objects which you submitted in #24 . Did not know about that one.

Yeah, that's actually one of the first things I learned in pathlib, find it pretty cool hahah. But I used joinpath here to keep it uniform with the rest of the datasets.

**Comment by vinisalazar** [comment]
I think "/" is more elegant but less explicit for those unfamiliar with the library. I will consider a refactor.

**Comment by vinisalazar** [comment]
A nice-to-have would be to have tests run the blastn preset with the new blastdb. But I'd rather merge this as is for now.

**Comment by jvfe** [comment]
> A nice-to-have would be to have tests run the blastn preset with the new blastdb. But I'd rather merge this as is for now.

I agree, but that would be nice in another PR, as it would also require updating the environment and the github action, since it introduces a new dependency.

**Comment by vinisalazar** [comment]
> > A nice-to-have would be to have tests run the blastn preset with the new blastdb. But I'd rather merge this as is for now.
> 
> I agree, but that would be nice in another PR, as it would also require updating the environment and the github action, since it introduces a new dependency.

The dependency discussion is important. I guess I want to include blastn in the environment because it's such an ubiquitous tool. But I'm not sure if in the future I want to have all presets as dependencies (for example, Kaiju is not included as a dependency). Prodigal is also one I consider removing, but would require most tests to be refactored.

**Pull request merged**
